### ISSUE TITLE
luarocks not executable.

### ISSUE THREAD

**Issue by daurnimator** [keplerproject/luarocks#465]
@zash ran into an issue where luarocks wasn't installed with executable permissions:
```
-rwxr-x--- 1 root root 911 Dec  7 12:30 /usr/local/bin/luarocks-5.1
```

The `make install` rules ends up using `cp` (see https://github.com/keplerproject/luarocks/blob/e3203adbc3f5daa5f46097d3439edbada01807f3/Makefile.install.inc#L10).

The Makefile should use the `install` command instead.

**Comment by siffiejoe** [comment]
The usual objections is that `cp` is in POSIX, while `install` isn't. AFAICT, at least Linux, OSX, and FreeBSD have it though (and the most important command line flags are the same) ...

**Comment by Zash** [comment]
This could be configured or detected in `./configure`, right?

**Comment by siffiejoe** [comment]
Not in `./configure`, because the Makefile could run without previous configuring when updating LuaRocks via LuaRocks. But it could be detected in the Makefile itself (it would look ugly though). Maybe we should just call `chmod` (which is in POSIX) after copying ... (We probably should fix this problem even on platforms where `install` isn't available anyway!)

**Comment by hishamhm** [comment]
That's why I have my brain hardwired to the `zxvpf` sequence whenever I think of `tar` :) I suppose the tarball was extracted with `tar zxf` instead of `tar zxpf`...

The LR tarballs include the proper permissions, so making changes here would be in my view, not fixing a bug, but actually be protecting the users from themselves... but yes, we can add `chmod` to the Makefile. 

The code is rc-frozen for the next release though, so I'd prefer to take a PR for this for the next release only.

**Comment by daurnimator** [comment]
With the fix from 6217339 the files are executable but still not readable. i.e. `-rwxr-x--x`

**Comment by hishamhm** [comment]
If we have to start worrying if files are even _readable_, then this would apply to all files and there would be more work and testing to do. I can take a PR on this.

**Comment by daurnimator** [comment]
> If we have to start worrying if files are even readable, then this would apply to all files and there would be more work and testing to do. I can take a PR on this.

Anywhere we use `cp` we need to follow up with a `chmod +rx`. I see 3 remaining places:
  - https://github.com/keplerproject/luarocks/blob/6217339cd4ba6d7ee7f08aa86443032ede033752/Makefile#L129
  - https://github.com/keplerproject/luarocks/blob/6217339cd4ba6d7ee7f08aa86443032ede033752/Makefile.luarocks#L15
  - https://github.com/keplerproject/luarocks/blob/6217339cd4ba6d7ee7f08aa86443032ede033752/Makefile.install.inc#L21
